# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 

Name:       edbus
Summary:    D-Bus and HAL wrapper libraries for EFL
Version:    1.0.999.svn60291
Release:    1
Group:      TO_BE/FILLED_IN
License:    TO BE FILLED IN
Source0:    http://download.enlightenment.org/releases/edbus-%{version}.tar.bz2
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(ecore)
BuildRequires:  pkgconfig(eina)
BuildRequires:  pkgconfig(evas)
BuildRequires:  pkgconfig(dbus-1)


%description
D-Bus and HAL wrapper libraries for use with the EFL



%package devel
Summary:    D-Bus and HAL wrapper libraries for EFL (devel)
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
D-Bus and HAL wrapper libraries for use with the EFL (devel)


%prep
%setup -q -n %{name}


%build

%autogen --disable-static
%configure --disable-static
make %{?jobs:-j%jobs}

%install
rm -rf %{buildroot}
%make_install




%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
%{_libdir}/libedbus.so.*
%{_libdir}/libehal.so.*
%{_libdir}/libenotify.so.*
%{_libdir}/libeofono.so.*
%{_libdir}/libeconnman.so.*
%{_libdir}/libebluez.so.*
%{_libdir}/libeukit.so.*
/usr/bin/e-notify-send
/usr/bin/e_dbus_*


%files devel
%defattr(-,root,root,-)
%{_includedir}/e_dbus-1/*.h
%{_libdir}/libedbus.so
%{_libdir}/libehal.so
%{_libdir}/libenotify.so
%{_libdir}/libeofono.so
%{_libdir}/libeconnman.so
%{_libdir}/libebluez.so
%{_libdir}/libeukit.so
%{_libdir}/pkgconfig/e*.pc

